version: "3.3"

services:
  test:
    hostname: test
    image: puppetester:latest
    working_dir: /app/browser
    volumes:
      - ./tests:/app/browser
    environment:
      - TARGET_URL=http://localhost:8000/wp-login.php
    network_mode: "host"